<a href="https://colab.research.google.com/github/melisovlab/ml_intro/blob/main/(1)ml_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# создание матрицы 1000 на 50, элементы которой являются случайными из нормального распределения

X = np.random.normal(loc = 1, scale = 10, size = (1000, 50))
print(X)

[[  6.94542191  10.25709418  -2.88222512 ...  -2.86710808  18.39774112
    2.42397212]
 [ 10.63372457   9.46171464  13.49495836 ...   7.15241968 -20.4565705
   -0.59668357]
 [ -0.13182914  22.51686205   1.07726105 ...  10.13115907   4.36263553
   -0.22236987]
 ...
 [ 11.72295189 -11.48564244  -1.26082782 ...   9.8240031   12.35623261
   -9.99207003]
 [ 11.02842857   0.22586574  10.56938239 ...  -0.05606734   8.91636783
   -7.28801265]
 [  3.78200657  -5.81961773 -14.19079521 ...   0.26384108 -13.6174164
   -1.20602067]]


In [ ]:
# нормировка

print('DIVIDER')
m = np.mean(X, axis = 0)  # по столбцам
std = np.std(X, axis = 0)
X_norm = ((X - m) / std)
print(X_norm)

[[ 0.59950986  0.93128498 -0.38505882 ... -0.38354434  1.74684399
   0.14653492]
 [ 0.96901716  0.85160103  1.25566575 ...  0.62024764 -2.14571932
  -0.15608512]
 [-0.10951435  2.15951219  0.01161661 ...  0.91866836  0.34075712
  -0.11858504]
 ...
 [ 1.07813983 -1.2469798  -0.22262146 ...  0.88789638  1.14158415
  -1.0973484 ]
 [ 1.00856001 -0.07367921  0.96257113 ... -0.10192426  0.79696624
  -0.8264463 ]
 [ 0.28258765 -0.67933727 -1.51799164 ... -0.0698747  -1.46054851
  -0.21713068]]
DIVIDER
[[ 0.57382489  0.94307142 -0.40235615 ... -0.36266173  1.73315766
   0.17118509]
 [ 0.93709154  0.86246662  1.18205    ...  0.60932436 -2.10793751
  -0.12929616]
 [-0.12322455  2.18549232 -0.01929674 ...  0.8982894   0.34566232
  -0.09206112]
 ...
 [ 1.04437123 -1.26036593 -0.24549451 ...  0.86849246  1.13590067
  -1.063907  ]
 [ 0.97596655 -0.07350638  0.89901595 ... -0.089965    0.79583936
  -0.79491952]
 [ 0.2622552  -0.68616358 -1.49640069 ... -0.05893095 -1.43182615
  -0.18991028]]


In [ ]:
# show rows which sum is greater than 10

Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

Z_sr = np.sum(Z, axis = 1)
print(np.nonzero(Z_sr > 10)[0])




[1 4 5]


In [ ]:
# union of matrices

A = np.eye(3)
B = np.eye(3)

# C - matrice that is vertrically stacked with A and B
C = np.vstack((A, B))
print(C)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Переработка данных в Pandas (week 1)

In [ ]:
import pandas as pd

In [ ]:
# загрузка данных из репозитория

url = 'https://raw.githubusercontent.com/melisovlab/ml_intro/main/train_titanic.csv?token=AQEFYW3HXR3U5WYKTCK7X5DA6F7XW'
data = pd.read_csv(url, encoding = 'utf-8', index_col = 'PassengerId')

In [ ]:
data.head()

Survived  Pclass  ... Cabin Embarked
PassengerId                    ...               
1                   0       3  ...   NaN        S
2                   1       1  ...   C85        C
3                   1       3  ...   NaN        S
4                   1       1  ...  C123        S
5                   0       3  ...   NaN        S

[5 rows x 11 columns]

In [ ]:
data['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [ ]:
# 1 question: 'Какое количество мужчин и женщин ехало на корабле?'

data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [ ]:
# 2 question: 'Какой части пассажиров удалось выжить?
# Посчитайте долю выживших пассажиров. Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен),
# округлив до двух знаков.'

s = data['Survived'].value_counts()[1]
ns = data['Survived'].value_counts()[0]

print(round((s / (s + ns) * 100), 2))

38.38


In [ ]:
# question 3: 'Какую долю пассажиры первого класса составляли среди всех пассажиров?
# Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух знаков.'

data['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [ ]:
print(round((216 / (491 + 216 + 184) * 100), 2))

24.24


In [ ]:
# question 4: 'Какого возраста были пассажиры? Посчитайте среднее и медиану возраста пассажиров.
# Посчитайте среднее и медиану возраста пассажиров. В качестве ответа приведите два числа через пробел.'

print(round(data['Age'].mean(), 2))
print(data['Age'].median())

29.7
28.0


In [ ]:
# question 5: 'Коррелируют ли число братьев/сестер с числом родителей/детей?
# Посчитайте корреляцию Пирсона между признаками SibSp и Parch.'

round(data['SibSp'].corr(data['Parch'], method = 'pearson'), 2)

0.41

In [ ]:
# question 6: 'Какое самое популярное женское имя на корабле?
# Извлеките из полного имени пассажира (колонка Name) его личное имя (First Name).
# Это задание — типичный пример того, с чем сталкивается специалист по анализу данных.
# Данные очень разнородные и шумные, но из них требуется извлечь необходимую информацию.
# Попробуйте вручную разобрать несколько значений столбца Name и выработать правило для извлечения имен, а также разделения их на женские и мужские.'

names = data['Name']
sex = data['Sex']

f_names = names[sex.str.contains('female')]


In [ ]:
f_names

PassengerId
2      Cumings, Mrs. John Bradley (Florence Briggs Th...
3                                 Heikkinen, Miss. Laina
4           Futrelle, Mrs. Jacques Heath (Lily May Peel)
9      Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
10                   Nasser, Mrs. Nicholas (Adele Achem)
                             ...                        
881         Shelley, Mrs. William (Imanita Parrish Hall)
883                         Dahlberg, Miss. Gerda Ulrika
886                 Rice, Mrs. William (Margaret Norton)
888                         Graham, Miss. Margaret Edith
889             Johnston, Miss. Catherine Helen "Carrie"
Name: Name, Length: 314, dtype: object

In [ ]:
test = f_names

KeyError: ignored